
platform :ios, '12.0'

target 'Agents Partner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Agents Partner
  pod 'RealmSwift'
end
